import { Button } from "@mui/material";

const UserCard = () => {
  const users = [
    {
      id: 1,
      name: "Alex Nguyen",
      teach: ["JavaScript", "HTML/CSS"],
      learn: ["UI/UX Design", "Graphic Design"],
      bio: "Frontend developer who loves clean code.",
      avatar: "https://i.pravatar.cc/150?img=1",
      followers: [2, 3, 4],
      following: [2, 3, 4],
      workplace: "QuantumSynergy DataDynamics Solutions Incorporated",
      position: "Frontend Developer",
      gender: "Male",
      pronouns: "He / Him",
      age: 28,
      language: "English",
    },
    {
      id: 2,
      name: "Bella Reyes",
      teach: ["UI/UX Design", "Storytelling"],
      learn: ["JavaScript", "APIs"],
      bio: "Designer curious about frontend dev.",
      avatar: "https://i.pravatar.cc/150?img=2",
      followers: [1],
      following: [1],
      workplace: "CreativeFlow Studio",
      position: "UI/UX Designer",
      gender: "Female",
      pronouns: "She / Her",
      age: 25,
      language: "Spanish",
    },
    {
      id: 3,
      name: "Chris Patel",
      teach: ["JavaScript", "Python Programming", "Data Analysis"],
      learn: ["Project Management", "Team Management"],
      bio: "Data lover moving into tech leadership.",
      avatar: "https://i.pravatar.cc/150?img=3",
      followers: [4],
      following: [4, 1],
      workplace: "DataSync Solutions",
      position: "Data Analyst",
      gender: "Male",
      pronouns: "He / Him",
      age: 32,
      language: "English",
    },
    {
      id: 4,
      name: "Dana Tran",
      teach: ["Project Management", "Delegation"],
      learn: ["Python Programming", "SQL"],
      bio: "Agile coach exploring coding for automation.",
      avatar: "https://i.pravatar.cc/150?img=4",
      followers: [3],
      following: [3, 1],
      workplace: "AgileWorks Consulting",
      position: "Project Manager",
      gender: "Female",
      pronouns: "She / Her",
      age: 38,
      language: "Mandarin",
    },
    {
      id: 5,
      name: "Eli Tanaka",
      teach: ["React", "Git & Version Control"],
      learn: ["Digital Marketing", "Storytelling"],
      bio: "Frontend nerd learning how to reach users.",
      avatar: "https://i.pravatar.cc/150?img=5",
      followers: [],
      following: [],
      workplace: "CodeZap Technologies",
      position: "React Developer",
      gender: "Female",
      pronouns: "They / Them",
      age: 27,
      language: "French",
    },
    {
      id: 6,
      name: "Fiona Chen",
      teach: ["Digital Marketing", "Ideation Techniques"],
      learn: ["React", "JavaScript"],
      bio: "Growth hacker interested in frontend magic.",
      avatar: "https://i.pravatar.cc/150?img=6",
      followers: [],
      following: [],
      workplace: "GrowthSpark Agency",
      position: "Digital Marketing Specialist",
      gender: "Female",
      pronouns: "She / Her",
      age: 30,
      language: "English",
    },
    {
      id: 7,
      name: "George Singh",
      teach: ["Public Speaking", "Persuasion"],
      learn: ["Node.js", "APIs"],
      bio: "TEDx speaker getting into backend development.",
      avatar: "https://i.pravatar.cc/150?img=7",
      followers: [],
      following: [],
      workplace: "InspireTalk Events",
      position: "Public Speaking Coach",
      gender: "Male",
      pronouns: "He / Him",
      age: 45,
      language: "English",
    },
    {
      id: 8,
      name: "Zane Smith",
      teach: ["Cloud Architecture", "Storytelling"],
      learn: ["DevOps", "Git"],
      bio: "Constantly learning, always curious.",
      avatar: "https://i.pravatar.cc/150?img=26",
      followers: [],
      following: [],
      workplace: "NextGen Soft",
      position: "Backend Developer",
      gender: "Male",
      pronouns: "He / Him",
      age: 45,
      language: "English",
    },
    {
      id: 9,
      name: "John Johnson",
      teach: ["UI/UX Design", "Digital Marketing"],
      learn: ["Go", "DevOps"],
      bio: "Helping teams thrive through leadership.",
      avatar: "https://i.pravatar.cc/150?img=60",
      followers: [],
      following: [],
      workplace: "AIWorks",
      position: "DevOps Engineer",
      gender: "Female",
      pronouns: "She / Her",
      age: 42,
      language: "Chinese",
    },
    {
      id: 10,
      name: "Jenny Wang",
      teach: ["Rust", "UI/UX Design"],
      learn: ["DevOps", "Go"],
      bio: "Passionate about building scalable systems.",
      avatar: "https://i.pravatar.cc/150?img=10",
      followers: [],
      following: [],
      workplace: "AIWorks",
      position: "Full Stack Developer",
      gender: "Female",
      pronouns: "She / Her",
      age: 24,
      language: "Chinese",
    },
    {
      id: 11,
      name: "Felix Costa",
      teach: ["Vue", "Machine Learning"],
      learn: ["Leadership", "Storytelling"],
      bio: "Automation enthusiast and agile advocate.",
      avatar: "https://i.pravatar.cc/150?img=32",
      followers: [],
      following: [],
      workplace: "CodeNest",
      position: "Frontend Developer",
      gender: "Male",
      pronouns: "He / Him",
      age: 46,
      language: "Portuguese",
    },
    {
      id: 12,
      name: "Willow Hart",
      teach: ["DevOps", "UI/UX Design"],
      learn: ["SQL", "Machine Learning"],
      bio: "Design thinker and front-end explorer.",
      avatar: "https://i.pravatar.cc/150?img=23",
      followers: [],
      following: [],
      workplace: "Innovatech",
      position: "DevOps Engineer",
      gender: "Female",
      pronouns: "They / Them",
      age: 27,
      language: "English",
    },
    {
      id: 13,
      name: "Priya Singh",
      teach: ["Git", "Java"],
      learn: ["Public Speaking", "Machine Learning"],
      bio: "Dreaming in code and color.",
      avatar: "https://i.pravatar.cc/150?img=16",
      followers: [],
      following: [],
      workplace: "CloudCore Labs",
      position: "Software Engineer",
      gender: "Female",
      pronouns: "She / Her",
      age: 35,
      language: "Punjabi",
    },
    {
      id: 14,
      name: "Sasha Petrov",
      teach: ["Rust", "SQL"],
      learn: ["Digital Marketing", "React"],
      bio: "Bridging tech and storytelling.",
      avatar: "https://i.pravatar.cc/150?img=19",
      followers: [],
      following: [],
      workplace: "DevGenius Solutions",
      position: "Backend Developer",
      gender: "Male",
      pronouns: "He / Him",
      age: 31,
      language: "Russian",
    },
    {
      id: 15,
      name: "Cleo Adams",
      teach: ["Agile", "Go"],
      learn: ["Vue", "Machine Learning"],
      bio: "Constantly learning, always curious.",
      avatar: "https://i.pravatar.cc/150?img=29",
      followers: [],
      following: [],
      workplace: "PixelPerfect Studio",
      position: "Agile Coach",
      gender: "Female",
      pronouns: "They / Them",
      age: 34,
      language: "English",
    },
    {
      id: 16,
      name: "Ava Johnson",
      teach: ["Leadership", "DevOps"],
      learn: ["Vue", "Graphic Design"],
      bio: "Helping teams thrive through leadership.",
      avatar: "https://i.pravatar.cc/150?img=27",
      followers: [],
      following: [],
      workplace: "BrightSpark Co.",
      position: "Tech Lead",
      gender: "Female",
      pronouns: "She / Her",
      age: 29,
      language: "English",
    },
    {
      id: 17,
      name: "Derek Choi",
      teach: ["Java", "Git"],
      learn: ["Public Speaking", "UI/UX Design"],
      bio: "Creative soul with a love for UI.",
      avatar: "https://i.pravatar.cc/150?img=30",
      followers: [],
      following: [],
      workplace: "TechNova Inc.",
      position: "Software Engineer",
      gender: "Male",
      pronouns: "He / Him",
      age: 33,
      language: "Korean",
    },
    {
      id: 18,
      name: "Ben Torres",
      teach: ["Python", "Machine Learning"],
      learn: ["Cloud Architecture", "Graphic Design"],
      bio: "Passionate about building scalable systems.",
      avatar: "https://i.pravatar.cc/150?img=28",
      followers: [],
      following: [],
      workplace: "AIWorks",
      position: "Machine Learning Engineer",
      gender: "Male",
      pronouns: "He / Him",
      age: 28,
      language: "Spanish",
    },
    {
      id: 19,
      name: "Oscar Müller",
      teach: ["React", "Node.js"],
      learn: ["Digital Marketing", "DevOps"],
      bio: "Loves mentoring and sharing knowledge.",
      avatar: "https://i.pravatar.cc/150?img=15",
      followers: [],
      following: [],
      workplace: "ByteBuilders",
      position: "Full Stack Developer",
      gender: "Male",
      pronouns: "He / Him",
      age: 37,
      language: "German",
    },
    {
      id: 20,
      name: "Nina Russo",
      teach: ["Storytelling", "UI/UX Design"],
      learn: ["Java", "APIs"],
      bio: "Bridging tech and storytelling.",
      avatar: "https://i.pravatar.cc/150?img=14",
      followers: [],
      following: [],
      workplace: "PixelPerfect Studio",
      position: "UX Researcher",
      gender: "Female",
      pronouns: "She / Her",
      age: 31,
      language: "Italian",
    },
    {
      id: 21,
      name: "Kai Yamamoto",
      teach: ["Python", "Graphic Design"],
      learn: ["Git", "Public Speaking"],
      bio: "Creative soul with a love for UI.",
      avatar: "https://i.pravatar.cc/150?img=11",
      followers: [],
      following: [],
      workplace: "BrightSpark Co.",
      position: "UI Designer",
      gender: "Male",
      pronouns: "He / Him",
      age: 25,
      language: "Japanese",
    },
    {
      id: 22,
      name: "Victor Chan",
      teach: ["Cloud Architecture", "Agile"],
      learn: ["Vue", "Public Speaking"],
      bio: "Design thinker and front-end explorer.",
      avatar: "https://i.pravatar.cc/150?img=22",
      followers: [],
      following: [],
      workplace: "NextGen Soft",
      position: "Product Manager",
      gender: "Male",
      pronouns: "He / Him",
      age: 44,
      language: "Cantonese",
    },
    {
      id: 23,
      name: "Ella Zhang",
      teach: ["SQL", "Graphic Design"],
      learn: ["Storytelling", "JavaScript"],
      bio: "Data-driven but people-first.",
      avatar: "https://i.pravatar.cc/150?img=31",
      followers: [],
      following: [],
      workplace: "TechNova Inc.",
      position: "Frontend Developer",
      gender: "Female",
      pronouns: "She / Her",
      age: 27,
      language: "Mandarin",
    },
    {
      id: 24,
      name: "Yasmine Farah",
      teach: ["Machine Learning", "DevOps"],
      learn: ["Rust", "Agile"],
      bio: "Automation enthusiast and agile advocate.",
      avatar: "https://i.pravatar.cc/150?img=25",
      followers: [],
      following: [],
      workplace: "Innovatech",
      position: "DevOps Engineer",
      gender: "Female",
      pronouns: "She / Her",
      age: 40,
      language: "Arabic",
    },
    {
      id: 25,
      name: "Hana Kim",
      teach: ["Digital Marketing", "APIs"],
      learn: ["Go", "JavaScript"],
      bio: "Constantly learning, always curious.",
      avatar: "https://i.pravatar.cc/150?img=44",
      followers: [],
      following: [],
      workplace: "GrowthSpark Agency",
      position: "Marketing Strategist",
      gender: "Female",
      pronouns: "She / Her",
      age: 26,
      language: "Korean",
    },
    {
      id: 26,
      name: "Uma Nair",
      teach: ["Graphic Design", "React"],
      learn: ["Agile", "SQL"],
      bio: "Dreaming in code and color.",
      avatar: "https://i.pravatar.cc/150?img=21",
      followers: [],
      following: [],
      workplace: "CodeNest",
      position: "Frontend Developer",
      gender: "Female",
      pronouns: "She / Her",
      age: 30,
      language: "Malayalam",
    },
    {
      id: 27,
      name: "Marcus Lee",
      teach: ["JavaScript", "Machine Learning"],
      learn: ["Storytelling", "Vue"],
      bio: "Passionate about building scalable systems.",
      avatar: "https://i.pravatar.cc/150?img=13",
      followers: [],
      following: [],
      workplace: "DevGenius Solutions",
      position: "Machine Learning Engineer",
      gender: "Male",
      pronouns: "He / Him",
      age: 36,
      language: "English",
    },
    {
      id: 28,
      name: "Ibrahim Ali",
      teach: ["SQL", "APIs"],
      learn: ["React", "Digital Marketing"],
      bio: "Data-driven but people-first.",
      avatar: "https://i.pravatar.cc/150?img=9",
      followers: [],
      following: [],
      workplace: "BrightSpark Co.",
      position: "Backend Developer",
      gender: "Male",
      pronouns: "He / Him",
      age: 34,
      language: "Arabic",
    },
    {
      id: 29,
      name: "Quinn O'Brien",
      teach: ["Leadership", "Public Speaking"],
      learn: ["Node.js", "Git"],
      bio: "Helping teams thrive through leadership.",
      avatar: "https://i.pravatar.cc/150?img=17",
      followers: [],
      following: [],
      workplace: "InspireTalk Events",
      position: "Public Speaking Coach",
      gender: "Male",
      pronouns: "He / Him",
      age: 41,
      language: "Irish",
    },
    {
      id: 30,
      name: "Tina Lopez",
      teach: ["Digital Marketing", "UI/UX Design"],
      learn: ["Python", "Go"],
      bio: "Creative soul with a love for UI.",
      avatar: "https://i.pravatar.cc/150?img=20",
      followers: [],
      following: [],
      workplace: "GrowthSpark Agency",
      position: "UX Researcher",
      gender: "Female",
      pronouns: "She / Her",
      age: 29,
      language: "Spanish",
    },
  ];

  return (
    <div className="relative flex flex-col items-center">
      <div
        className="w-[180px] h-[265px] bg-white rounded-[20px] shadow-[0_4px_16px_rgba(0,0,0,0.30)] overflow-hidden flex flex-col items-center font-roboto cursor-pointer
                        "
      >
        {/* Top Banner + Avatar */}
        <div className="w-full relative">
          <div className="w-full h-[60px] bg-[#016D75]" />
          <img
            src={user.avatar}
            alt={user.name}
            className="absolute top-[25px] left-1/2 -translate-x-1/2 w-[90px] h-[90px] rounded-full object-cover"
          />

          {typeof matchCount === "number" && matchCount > 0 && (
            <img
              src="/assets/Badge.png"
              alt="Match Badge"
              className="absolute top-[85px] left-[42px] w-[90px] rotate-[-25deg] z-10"
            />
          )}
        </div>

        {/* Name */}
        <h3 className="mt-[70px] text-[16px] font-bold text-[#152438] text-center px-4 w-[160px] truncate">
          {user.name}
        </h3>

        {/* Workplace & Position */}
        <div className="mt-[5px] w-[160px] text-[14px] text-[#575859] leading-tight text-center space-y-0">
          {user.workplace && (
            <div className="font-semibold truncate">{user.workplace}</div>
          )}
          {user.position && (
            <div className="text-[13px] font-light truncate">
              {user.position}
            </div>
          )}
        </div>
      </div>
      {/* Connect Button */}
      <div className="mt-4 mb-3 absolute bottom-3">
        <Button>Connect</Button>
      </div>
    </div>
  );
};

export default UserCard;
